#!/usr/bin/env python3
"""Convert the Workstream D program workbook into data/programs.js for the dashboard.

Usage:
    pip install pandas openpyxl
    python scripts/build_data.py "path/to/Workstream D Analysis.xlsx"

The workbook must have one sheet (the first is used) with the column headers
listed in COLUMNS below. Re-run this whenever the workbook changes, then commit
data/programs.js.
"""
import json
import sys
from pathlib import Path

import pandas as pd

COLUMNS = {
    "id": "APR Program ID", "nm": "Informal Program Name", "full": "Program name",
    "fac": "Faculty", "dept": "Department", "type": "Program type", "cred": "Credential type",
    "cip": "CIP name", "st": "Status", "e21": "2021-22 enrolment", "e24": "2024-25 enrolment",
    "c3": "3-year CAGR", "c10": "10-year CAGR", "e10": "10-year average enrolment",
    "chp": "Total CHP", "cost": "Total cost", "rev": "Total revenue", "mar": "Total margin",
    "mpc": "Margin per CHP", "tbl": "Costing table", "thr": "Applicable threshold",
    "lma": "LMA signal", "emp": "Employment outcome", "pv": "Public value",
    "cat": "Agreed Workstream C category", "cred24": "Dal credentials 2024",
    "ns24": "NS credentials 2024", "ms": "Market share 2024", "mst": "Market share trend",
    "mkt": "Market size trend", "cr10": "Credentials 10-year total",
    "grad": "Graduation trend categorization", "res": "Research Contribution",
    "cur": "Curriculum Trend Signal", "th": "Thesis Type",
}
LEVELS = {
    "Undergraduate program": "UG",
    "Graduate program (second cycle)": "Masters",
    "Graduate program (third cycle)": "Doctoral",
    "Career, technical or professional training program": "Diploma/Tech",
    "Post-baccalaureate non-graduate program": "Post-bacc",
}


def num(x):
    if pd.isna(x):
        return None
    x = float(x)
    return round(x, 4) if abs(x) < 10 else round(x, 1)


def text(x):
    return "" if pd.isna(x) else str(x).strip()


def main(path):
    df = pd.read_excel(path)
    missing = [c for c in COLUMNS.values() if c not in df.columns]
    if missing:
        sys.exit("Missing columns in workbook: " + ", ".join(missing))
    c = COLUMNS
    rows = []
    for _, r in df.iterrows():
        cat = text(r[c["cat"]])
        if cat.lower().startswith("no change"):
            cat = "No Change"
        st = text(r[c["st"]])
        if "termination" in st.lower():
            st = "Suspended (to termination)"
        rows.append({
            "id": int(r[c["id"]]), "nm": text(r[c["nm"]]), "full": text(r[c["full"]]),
            "fac": text(r[c["fac"]]), "dept": text(r[c["dept"]]),
            "lv": LEVELS.get(text(r[c["type"]]), text(r[c["type"]])),
            "cred": text(r[c["cred"]]), "cip": text(r[c["cip"]]), "st": st,
            "e21": num(r[c["e21"]]), "e24": num(r[c["e24"]]), "c3": num(r[c["c3"]]),
            "c10": num(r[c["c10"]]), "e10": num(r[c["e10"]]), "chp": num(r[c["chp"]]),
            "cost": num(r[c["cost"]]), "rev": num(r[c["rev"]]), "mar": num(r[c["mar"]]),
            "mpc": num(r[c["mpc"]]), "tbl": 1 if text(r[c["tbl"]]) == "Table 1" else 2,
            "thr": int(r[c["thr"]]),
            "lma": None if pd.isna(r[c["lma"]]) else int(r[c["lma"]]),
            "emp": text(r[c["emp"]]), "pv": text(r[c["pv"]]), "cat": cat,
            "cred24": num(r[c["cred24"]]), "ns24": num(r[c["ns24"]]), "ms": num(r[c["ms"]]),
            "mst": text(r[c["mst"]]), "mkt": text(r[c["mkt"]]), "cr10": num(r[c["cr10"]]),
            "grad": text(r[c["grad"]]),
            "res": 1 if text(r[c["res"]]) == "Research Priority Aligned" else 0,
            "cur": None if pd.isna(r[c["cur"]]) else int(r[c["cur"]]), "th": text(r[c["th"]]),
        })
    out = Path(__file__).resolve().parent.parent / "data" / "programs.js"
    payload = json.dumps(rows, separators=(",", ":"), ensure_ascii=False).replace("</", "<\\/")
    out.write_text("/* Generated by scripts/build_data.py. Do not edit by hand. */\nwindow.APR_DATA = " + payload + ";\n", encoding="utf-8")
    print(f"Wrote {len(rows)} programs to {out}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
